//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace WARP.XrmSolutionValidator.Core.XrmModels {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Descriptions {
        
        private DescriptionsDescription[] descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Description", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DescriptionsDescription[] Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DescriptionsDescription {
        
        private string descriptionField;
        
        private string languagecodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string languagecode {
            get {
                return this.languagecodeField;
            }
            set {
                this.languagecodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class displaynames {
        
        private displaynamesDisplayname[] displaynameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("displayname", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public displaynamesDisplayname[] displayname {
            get {
                return this.displaynameField;
            }
            set {
                this.displaynameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class displaynamesDisplayname {
        
        private string descriptionField;
        
        private string languagecodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string languagecode {
            get {
                return this.languagecodeField;
            }
            set {
                this.languagecodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class labels {
        
        private labelsLabel[] labelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("label", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public labelsLabel[] label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class labelsLabel {
        
        private string descriptionField;
        
        private string languagecodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string languagecode {
            get {
                return this.languagecodeField;
            }
            set {
                this.languagecodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Entity {
        
        private string objectTypeCodeField;
        
        private string formXmlField;
        
        private string savedQueriesField;
        
        private string ribbonDiffXmlField;
        
        private EntityName[] nameField;
        
        private EntityEntityInfoEntity[] entityInfoField;
        
        private EntityCustomControlDefaultConfigsCustomControlDefaultConfig[] customControlDefaultConfigsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ObjectTypeCode {
            get {
                return this.objectTypeCodeField;
            }
            set {
                this.objectTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FormXml {
            get {
                return this.formXmlField;
            }
            set {
                this.formXmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SavedQueries {
            get {
                return this.savedQueriesField;
            }
            set {
                this.savedQueriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RibbonDiffXml {
            get {
                return this.ribbonDiffXmlField;
            }
            set {
                this.ribbonDiffXmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public EntityName[] Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entity", typeof(EntityEntityInfoEntity), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EntityEntityInfoEntity[] EntityInfo {
            get {
                return this.entityInfoField;
            }
            set {
                this.entityInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("CustomControlDefaultConfig", typeof(EntityCustomControlDefaultConfigsCustomControlDefaultConfig), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EntityCustomControlDefaultConfigsCustomControlDefaultConfig[] CustomControlDefaultConfigs {
            get {
                return this.customControlDefaultConfigsField;
            }
            set {
                this.customControlDefaultConfigsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class EntityName {
        
        private string localizedNameField;
        
        private string originalNameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LocalizedName {
            get {
                return this.localizedNameField;
            }
            set {
                this.localizedNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OriginalName {
            get {
                return this.originalNameField;
            }
            set {
                this.originalNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class EntityEntityInfoEntity {
        
        private string entitySetNameField;
        
        private string isDuplicateCheckSupportedField;
        
        private string isBusinessProcessEnabledField;
        
        private string isRequiredOfflineField;
        
        private string isInteractionCentricEnabledField;
        
        private string isCollaborationField;
        
        private string autoRouteToOwnerQueueField;
        
        private string isConnectionsEnabledField;
        
        private string entityColorField;
        
        private string isDocumentManagementEnabledField;
        
        private string isOneNoteIntegrationEnabledField;
        
        private string isKnowledgeManagementEnabledField;
        
        private string isSLAEnabledField;
        
        private string isDocumentRecommendationsEnabledField;
        
        private string isBPFEntityField;
        
        private string ownershipTypeMaskField;
        
        private string entityMaskField;
        
        private string isAuditEnabledField;
        
        private string isActivityField;
        
        private string activityTypeMaskField;
        
        private string isActivityPartyField;
        
        private string isReplicatedField;
        
        private string isReplicationUserFilteredField;
        
        private string isMailMergeEnabledField;
        
        private string isVisibleInMobileField;
        
        private string isVisibleInMobileClientField;
        
        private string isReadOnlyInMobileClientField;
        
        private string isOfflineInMobileClientField;
        
        private string daysSinceRecordLastModifiedField;
        
        private string mobileOfflineFiltersField;
        
        private string isMapiGridEnabledField;
        
        private string isReadingPaneEnabledField;
        
        private string isQuickCreateEnabledField;
        
        private string syncToExternalSearchIndexField;
        
        private string introducedVersionField;
        
        private string isCustomizableField;
        
        private string isRenameableField;
        
        private string isMappableField;
        
        private string canModifyAuditSettingsField;
        
        private string canModifyMobileVisibilityField;
        
        private string canModifyMobileClientVisibilityField;
        
        private string canModifyMobileClientReadOnlyField;
        
        private string canModifyMobileClientOfflineField;
        
        private string canModifyConnectionSettingsField;
        
        private string canModifyDuplicateDetectionSettingsField;
        
        private string canModifyMailMergeSettingsField;
        
        private string canModifyQueueSettingsField;
        
        private string canCreateAttributesField;
        
        private string canCreateFormsField;
        
        private string canCreateChartsField;
        
        private string canCreateViewsField;
        
        private string canModifyAdditionalSettingsField;
        
        private string canEnableSyncToExternalSearchIndexField;
        
        private string iconMediumNameField;
        
        private string iconSmallNameField;
        
        private string enforceStateTransitionsField;
        
        private string canChangeHierarchicalRelationshipField;
        
        private string entityHelpUrlEnabledField;
        
        private string entityHelpUrlField;
        
        private string changeTrackingEnabledField;
        
        private string canChangeTrackingBeEnabledField;
        
        private string isEnabledForExternalChannelsField;
        
        private string hasRelatedActivitiesField;
        
        private EntityEntityInfoEntityLocalizedNamesLocalizedName[] localizedNamesField;
        
        private EntityEntityInfoEntityLocalizedCollectionNamesLocalizedCollectionName[] localizedCollectionNamesField;
        
        private DescriptionsDescription[] descriptionsField;
        
        private EntityEntityInfoEntityAttributesAttribute[] attributesField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EntitySetName {
            get {
                return this.entitySetNameField;
            }
            set {
                this.entitySetNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsDuplicateCheckSupported {
            get {
                return this.isDuplicateCheckSupportedField;
            }
            set {
                this.isDuplicateCheckSupportedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsBusinessProcessEnabled {
            get {
                return this.isBusinessProcessEnabledField;
            }
            set {
                this.isBusinessProcessEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsRequiredOffline {
            get {
                return this.isRequiredOfflineField;
            }
            set {
                this.isRequiredOfflineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsInteractionCentricEnabled {
            get {
                return this.isInteractionCentricEnabledField;
            }
            set {
                this.isInteractionCentricEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsCollaboration {
            get {
                return this.isCollaborationField;
            }
            set {
                this.isCollaborationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AutoRouteToOwnerQueue {
            get {
                return this.autoRouteToOwnerQueueField;
            }
            set {
                this.autoRouteToOwnerQueueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsConnectionsEnabled {
            get {
                return this.isConnectionsEnabledField;
            }
            set {
                this.isConnectionsEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EntityColor {
            get {
                return this.entityColorField;
            }
            set {
                this.entityColorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsDocumentManagementEnabled {
            get {
                return this.isDocumentManagementEnabledField;
            }
            set {
                this.isDocumentManagementEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsOneNoteIntegrationEnabled {
            get {
                return this.isOneNoteIntegrationEnabledField;
            }
            set {
                this.isOneNoteIntegrationEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsKnowledgeManagementEnabled {
            get {
                return this.isKnowledgeManagementEnabledField;
            }
            set {
                this.isKnowledgeManagementEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsSLAEnabled {
            get {
                return this.isSLAEnabledField;
            }
            set {
                this.isSLAEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsDocumentRecommendationsEnabled {
            get {
                return this.isDocumentRecommendationsEnabledField;
            }
            set {
                this.isDocumentRecommendationsEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsBPFEntity {
            get {
                return this.isBPFEntityField;
            }
            set {
                this.isBPFEntityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OwnershipTypeMask {
            get {
                return this.ownershipTypeMaskField;
            }
            set {
                this.ownershipTypeMaskField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EntityMask {
            get {
                return this.entityMaskField;
            }
            set {
                this.entityMaskField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsAuditEnabled {
            get {
                return this.isAuditEnabledField;
            }
            set {
                this.isAuditEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsActivity {
            get {
                return this.isActivityField;
            }
            set {
                this.isActivityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ActivityTypeMask {
            get {
                return this.activityTypeMaskField;
            }
            set {
                this.activityTypeMaskField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsActivityParty {
            get {
                return this.isActivityPartyField;
            }
            set {
                this.isActivityPartyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsReplicated {
            get {
                return this.isReplicatedField;
            }
            set {
                this.isReplicatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsReplicationUserFiltered {
            get {
                return this.isReplicationUserFilteredField;
            }
            set {
                this.isReplicationUserFilteredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsMailMergeEnabled {
            get {
                return this.isMailMergeEnabledField;
            }
            set {
                this.isMailMergeEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsVisibleInMobile {
            get {
                return this.isVisibleInMobileField;
            }
            set {
                this.isVisibleInMobileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsVisibleInMobileClient {
            get {
                return this.isVisibleInMobileClientField;
            }
            set {
                this.isVisibleInMobileClientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsReadOnlyInMobileClient {
            get {
                return this.isReadOnlyInMobileClientField;
            }
            set {
                this.isReadOnlyInMobileClientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsOfflineInMobileClient {
            get {
                return this.isOfflineInMobileClientField;
            }
            set {
                this.isOfflineInMobileClientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DaysSinceRecordLastModified {
            get {
                return this.daysSinceRecordLastModifiedField;
            }
            set {
                this.daysSinceRecordLastModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MobileOfflineFilters {
            get {
                return this.mobileOfflineFiltersField;
            }
            set {
                this.mobileOfflineFiltersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsMapiGridEnabled {
            get {
                return this.isMapiGridEnabledField;
            }
            set {
                this.isMapiGridEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsReadingPaneEnabled {
            get {
                return this.isReadingPaneEnabledField;
            }
            set {
                this.isReadingPaneEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsQuickCreateEnabled {
            get {
                return this.isQuickCreateEnabledField;
            }
            set {
                this.isQuickCreateEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SyncToExternalSearchIndex {
            get {
                return this.syncToExternalSearchIndexField;
            }
            set {
                this.syncToExternalSearchIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IntroducedVersion {
            get {
                return this.introducedVersionField;
            }
            set {
                this.introducedVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsCustomizable {
            get {
                return this.isCustomizableField;
            }
            set {
                this.isCustomizableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsRenameable {
            get {
                return this.isRenameableField;
            }
            set {
                this.isRenameableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsMappable {
            get {
                return this.isMappableField;
            }
            set {
                this.isMappableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CanModifyAuditSettings {
            get {
                return this.canModifyAuditSettingsField;
            }
            set {
                this.canModifyAuditSettingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CanModifyMobileVisibility {
            get {
                return this.canModifyMobileVisibilityField;
            }
            set {
                this.canModifyMobileVisibilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CanModifyMobileClientVisibility {
            get {
                return this.canModifyMobileClientVisibilityField;
            }
            set {
                this.canModifyMobileClientVisibilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CanModifyMobileClientReadOnly {
            get {
                return this.canModifyMobileClientReadOnlyField;
            }
            set {
                this.canModifyMobileClientReadOnlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CanModifyMobileClientOffline {
            get {
                return this.canModifyMobileClientOfflineField;
            }
            set {
                this.canModifyMobileClientOfflineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CanModifyConnectionSettings {
            get {
                return this.canModifyConnectionSettingsField;
            }
            set {
                this.canModifyConnectionSettingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CanModifyDuplicateDetectionSettings {
            get {
                return this.canModifyDuplicateDetectionSettingsField;
            }
            set {
                this.canModifyDuplicateDetectionSettingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CanModifyMailMergeSettings {
            get {
                return this.canModifyMailMergeSettingsField;
            }
            set {
                this.canModifyMailMergeSettingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CanModifyQueueSettings {
            get {
                return this.canModifyQueueSettingsField;
            }
            set {
                this.canModifyQueueSettingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CanCreateAttributes {
            get {
                return this.canCreateAttributesField;
            }
            set {
                this.canCreateAttributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CanCreateForms {
            get {
                return this.canCreateFormsField;
            }
            set {
                this.canCreateFormsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CanCreateCharts {
            get {
                return this.canCreateChartsField;
            }
            set {
                this.canCreateChartsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CanCreateViews {
            get {
                return this.canCreateViewsField;
            }
            set {
                this.canCreateViewsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CanModifyAdditionalSettings {
            get {
                return this.canModifyAdditionalSettingsField;
            }
            set {
                this.canModifyAdditionalSettingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CanEnableSyncToExternalSearchIndex {
            get {
                return this.canEnableSyncToExternalSearchIndexField;
            }
            set {
                this.canEnableSyncToExternalSearchIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IconMediumName {
            get {
                return this.iconMediumNameField;
            }
            set {
                this.iconMediumNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IconSmallName {
            get {
                return this.iconSmallNameField;
            }
            set {
                this.iconSmallNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EnforceStateTransitions {
            get {
                return this.enforceStateTransitionsField;
            }
            set {
                this.enforceStateTransitionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CanChangeHierarchicalRelationship {
            get {
                return this.canChangeHierarchicalRelationshipField;
            }
            set {
                this.canChangeHierarchicalRelationshipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EntityHelpUrlEnabled {
            get {
                return this.entityHelpUrlEnabledField;
            }
            set {
                this.entityHelpUrlEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EntityHelpUrl {
            get {
                return this.entityHelpUrlField;
            }
            set {
                this.entityHelpUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ChangeTrackingEnabled {
            get {
                return this.changeTrackingEnabledField;
            }
            set {
                this.changeTrackingEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CanChangeTrackingBeEnabled {
            get {
                return this.canChangeTrackingBeEnabledField;
            }
            set {
                this.canChangeTrackingBeEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsEnabledForExternalChannels {
            get {
                return this.isEnabledForExternalChannelsField;
            }
            set {
                this.isEnabledForExternalChannelsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HasRelatedActivities {
            get {
                return this.hasRelatedActivitiesField;
            }
            set {
                this.hasRelatedActivitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("LocalizedName", typeof(EntityEntityInfoEntityLocalizedNamesLocalizedName), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EntityEntityInfoEntityLocalizedNamesLocalizedName[] LocalizedNames {
            get {
                return this.localizedNamesField;
            }
            set {
                this.localizedNamesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("LocalizedCollectionName", typeof(EntityEntityInfoEntityLocalizedCollectionNamesLocalizedCollectionName), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EntityEntityInfoEntityLocalizedCollectionNamesLocalizedCollectionName[] LocalizedCollectionNames {
            get {
                return this.localizedCollectionNamesField;
            }
            set {
                this.localizedCollectionNamesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Description", typeof(DescriptionsDescription), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DescriptionsDescription[] Descriptions {
            get {
                return this.descriptionsField;
            }
            set {
                this.descriptionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("attribute", typeof(EntityEntityInfoEntityAttributesAttribute), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EntityEntityInfoEntityAttributesAttribute[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class EntityEntityInfoEntityLocalizedNamesLocalizedName {
        
        private string descriptionField;
        
        private string languagecodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string languagecode {
            get {
                return this.languagecodeField;
            }
            set {
                this.languagecodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class EntityEntityInfoEntityLocalizedCollectionNamesLocalizedCollectionName {
        
        private string descriptionField;
        
        private string languagecodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string languagecode {
            get {
                return this.languagecodeField;
            }
            set {
                this.languagecodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class EntityEntityInfoEntityAttributesAttribute {
        
        private string typeField;
        
        private string nameField;
        
        private string logicalNameField;
        
        private string requiredLevelField;
        
        private string displayMaskField;
        
        private string imeModeField;
        
        private string validForUpdateApiField;
        
        private string validForReadApiField;
        
        private string validForCreateApiField;
        
        private string isCustomFieldField;
        
        private string isAuditEnabledField;
        
        private string isLogicalField;
        
        private string isSecuredField;
        
        private string introducedVersionField;
        
        private string isCustomizableField;
        
        private string isRenameableField;
        
        private string canModifySearchSettingsField;
        
        private string canModifyRequirementLevelSettingsField;
        
        private string canModifyAdditionalSettingsField;
        
        private string sourceTypeField;
        
        private string isGlobalFilterEnabledField;
        
        private string isSortableEnabledField;
        
        private string canModifyGlobalFilterSettingsField;
        
        private string canModifyIsSortableSettingsField;
        
        private string formatField;
        
        private string minValueField;
        
        private string maxValueField;
        
        private string canChangeDateTimeBehaviorField;
        
        private string behaviorField;
        
        private string maxLengthField;
        
        private string lengthField;
        
        private string yomiOfField;
        
        private string appDefaultValueField;
        
        private string optionSetNameField;
        
        private string lookupStyleField;
        
        private EntityEntityInfoEntityAttributesAttributeOptionset[] optionsetField;
        
        private EntityEntityInfoEntityAttributesAttributeLookupTypesLookupType[] lookupTypesField;
        
        private displaynamesDisplayname[] displaynamesField;
        
        private DescriptionsDescription[] descriptionsField;
        
        private string physicalNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LogicalName {
            get {
                return this.logicalNameField;
            }
            set {
                this.logicalNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RequiredLevel {
            get {
                return this.requiredLevelField;
            }
            set {
                this.requiredLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DisplayMask {
            get {
                return this.displayMaskField;
            }
            set {
                this.displayMaskField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ImeMode {
            get {
                return this.imeModeField;
            }
            set {
                this.imeModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ValidForUpdateApi {
            get {
                return this.validForUpdateApiField;
            }
            set {
                this.validForUpdateApiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ValidForReadApi {
            get {
                return this.validForReadApiField;
            }
            set {
                this.validForReadApiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ValidForCreateApi {
            get {
                return this.validForCreateApiField;
            }
            set {
                this.validForCreateApiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsCustomField {
            get {
                return this.isCustomFieldField;
            }
            set {
                this.isCustomFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsAuditEnabled {
            get {
                return this.isAuditEnabledField;
            }
            set {
                this.isAuditEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsLogical {
            get {
                return this.isLogicalField;
            }
            set {
                this.isLogicalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsSecured {
            get {
                return this.isSecuredField;
            }
            set {
                this.isSecuredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IntroducedVersion {
            get {
                return this.introducedVersionField;
            }
            set {
                this.introducedVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsCustomizable {
            get {
                return this.isCustomizableField;
            }
            set {
                this.isCustomizableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsRenameable {
            get {
                return this.isRenameableField;
            }
            set {
                this.isRenameableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CanModifySearchSettings {
            get {
                return this.canModifySearchSettingsField;
            }
            set {
                this.canModifySearchSettingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CanModifyRequirementLevelSettings {
            get {
                return this.canModifyRequirementLevelSettingsField;
            }
            set {
                this.canModifyRequirementLevelSettingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CanModifyAdditionalSettings {
            get {
                return this.canModifyAdditionalSettingsField;
            }
            set {
                this.canModifyAdditionalSettingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SourceType {
            get {
                return this.sourceTypeField;
            }
            set {
                this.sourceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsGlobalFilterEnabled {
            get {
                return this.isGlobalFilterEnabledField;
            }
            set {
                this.isGlobalFilterEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsSortableEnabled {
            get {
                return this.isSortableEnabledField;
            }
            set {
                this.isSortableEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CanModifyGlobalFilterSettings {
            get {
                return this.canModifyGlobalFilterSettingsField;
            }
            set {
                this.canModifyGlobalFilterSettingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CanModifyIsSortableSettings {
            get {
                return this.canModifyIsSortableSettingsField;
            }
            set {
                this.canModifyIsSortableSettingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MinValue {
            get {
                return this.minValueField;
            }
            set {
                this.minValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MaxValue {
            get {
                return this.maxValueField;
            }
            set {
                this.maxValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CanChangeDateTimeBehavior {
            get {
                return this.canChangeDateTimeBehaviorField;
            }
            set {
                this.canChangeDateTimeBehaviorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Behavior {
            get {
                return this.behaviorField;
            }
            set {
                this.behaviorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MaxLength {
            get {
                return this.maxLengthField;
            }
            set {
                this.maxLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string YomiOf {
            get {
                return this.yomiOfField;
            }
            set {
                this.yomiOfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AppDefaultValue {
            get {
                return this.appDefaultValueField;
            }
            set {
                this.appDefaultValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OptionSetName {
            get {
                return this.optionSetNameField;
            }
            set {
                this.optionSetNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LookupStyle {
            get {
                return this.lookupStyleField;
            }
            set {
                this.lookupStyleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("optionset", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntityEntityInfoEntityAttributesAttributeOptionset[] optionset {
            get {
                return this.optionsetField;
            }
            set {
                this.optionsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("LookupType", typeof(EntityEntityInfoEntityAttributesAttributeLookupTypesLookupType), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntityEntityInfoEntityAttributesAttributeLookupTypesLookupType[] LookupTypes {
            get {
                return this.lookupTypesField;
            }
            set {
                this.lookupTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("displayname", typeof(displaynamesDisplayname), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public displaynamesDisplayname[] displaynames {
            get {
                return this.displaynamesField;
            }
            set {
                this.displaynamesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Description", typeof(DescriptionsDescription), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DescriptionsDescription[] Descriptions {
            get {
                return this.descriptionsField;
            }
            set {
                this.descriptionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PhysicalName {
            get {
                return this.physicalNameField;
            }
            set {
                this.physicalNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class EntityEntityInfoEntityAttributesAttributeOptionset {
        
        private string optionSetTypeField;
        
        private string introducedVersionField;
        
        private string isCustomizableField;
        
        private displaynamesDisplayname[] displaynamesField;
        
        private DescriptionsDescription[] descriptionsField;
        
        private EntityEntityInfoEntityAttributesAttributeOptionsetStatusesStatus[] statusesField;
        
        private EntityEntityInfoEntityAttributesAttributeOptionsetStatesState[] statesField;
        
        private EntityEntityInfoEntityAttributesAttributeOptionsetOptionsOption[] optionsField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OptionSetType {
            get {
                return this.optionSetTypeField;
            }
            set {
                this.optionSetTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IntroducedVersion {
            get {
                return this.introducedVersionField;
            }
            set {
                this.introducedVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsCustomizable {
            get {
                return this.isCustomizableField;
            }
            set {
                this.isCustomizableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("displayname", typeof(displaynamesDisplayname), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public displaynamesDisplayname[] displaynames {
            get {
                return this.displaynamesField;
            }
            set {
                this.displaynamesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Description", typeof(DescriptionsDescription), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DescriptionsDescription[] Descriptions {
            get {
                return this.descriptionsField;
            }
            set {
                this.descriptionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("status", typeof(EntityEntityInfoEntityAttributesAttributeOptionsetStatusesStatus), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EntityEntityInfoEntityAttributesAttributeOptionsetStatusesStatus[] statuses {
            get {
                return this.statusesField;
            }
            set {
                this.statusesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("state", typeof(EntityEntityInfoEntityAttributesAttributeOptionsetStatesState), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EntityEntityInfoEntityAttributesAttributeOptionsetStatesState[] states {
            get {
                return this.statesField;
            }
            set {
                this.statesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("option", typeof(EntityEntityInfoEntityAttributesAttributeOptionsetOptionsOption), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public EntityEntityInfoEntityAttributesAttributeOptionsetOptionsOption[] options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class EntityEntityInfoEntityAttributesAttributeOptionsetStatusesStatus {
        
        private labelsLabel[] labelsField;
        
        private string valueField;
        
        private string stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("label", typeof(labelsLabel), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public labelsLabel[] labels {
            get {
                return this.labelsField;
            }
            set {
                this.labelsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class EntityEntityInfoEntityAttributesAttributeOptionsetStatesState {
        
        private labelsLabel[] labelsField;
        
        private string valueField;
        
        private string defaultstatusField;
        
        private string invariantnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("label", typeof(labelsLabel), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public labelsLabel[] labels {
            get {
                return this.labelsField;
            }
            set {
                this.labelsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string defaultstatus {
            get {
                return this.defaultstatusField;
            }
            set {
                this.defaultstatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string invariantname {
            get {
                return this.invariantnameField;
            }
            set {
                this.invariantnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class EntityEntityInfoEntityAttributesAttributeOptionsetOptionsOption {
        
        private labelsLabel[] labelsField;
        
        private string valueField;
        
        private string colorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("label", typeof(labelsLabel), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public labelsLabel[] labels {
            get {
                return this.labelsField;
            }
            set {
                this.labelsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class EntityEntityInfoEntityAttributesAttributeLookupTypesLookupType {
        
        private string idField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class EntityCustomControlDefaultConfigsCustomControlDefaultConfig {
        
        private string primaryEntityTypeCodeField;
        
        private string customControlDefaultConfigIdField;
        
        private string introducedVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PrimaryEntityTypeCode {
            get {
                return this.primaryEntityTypeCodeField;
            }
            set {
                this.primaryEntityTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomControlDefaultConfigId {
            get {
                return this.customControlDefaultConfigIdField;
            }
            set {
                this.customControlDefaultConfigIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IntroducedVersion {
            get {
                return this.introducedVersionField;
            }
            set {
                this.introducedVersionField = value;
            }
        }
    }
}
